name: Android App Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/android/RunAnywhereAI/**'
      - '.github/workflows/android-app-lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/android/RunAnywhereAI/**'
      - '.github/workflows/android-app-lint.yml'

jobs:
  lint:
    name: Lint Android Example App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x ./examples/android/RunAnywhereAI/gradlew
      
    - name: Run lint
      working-directory: ./examples/android/RunAnywhereAI
      run: ./gradlew :app:lint
      
    - name: Upload lint results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: android-app-lint-results
        path: examples/android/RunAnywhereAI/app/build/reports/lint-results-*.html