name: iOS App Build

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/ios/RunAnywhereAI/**'
      - 'sdk/runanywhere-swift/**'
      - '.github/workflows/ios-app-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/ios/RunAnywhereAI/**'
      - 'sdk/runanywhere-swift/**'
      - '.github/workflows/ios-app-build.yml'

jobs:
  build:
    name: Build iOS Example App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Build SDK first
      working-directory: ./sdk/runanywhere-swift
      run: swift build
      
    - name: Resolve package dependencies
      working-directory: ./examples/ios/RunAnywhereAI
      run: |
        xcodebuild -resolvePackageDependencies \
          -project RunAnywhereAI.xcodeproj \
          -scheme RunAnywhereAI
          
    - name: Build app for iOS Simulator
      working-directory: ./examples/ios/RunAnywhereAI
      run: |
        xcodebuild build \
          -project RunAnywhereAI.xcodeproj \
          -scheme RunAnywhereAI \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          -configuration Debug \
          -derivedDataPath build
          
    - name: Run unit tests
      working-directory: ./examples/ios/RunAnywhereAI
      run: |
        xcodebuild test \
          -project RunAnywhereAI.xcodeproj \
          -scheme RunAnywhereAI \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          -resultBundlePath TestResults.xcresult
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-app-build
        path: examples/ios/RunAnywhereAI/build/Build/Products/
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ios-app-test-results
        path: examples/ios/RunAnywhereAI/TestResults.xcresult